// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ColortheGoalDaruma",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "ColortheGoalDaruma",
            targets: ["AppModule"],
            bundleIdentifier: "com.rino.ColortheGoalDaruma",
            teamIdentifier: "8W94AG6744",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .camera(purposeString: "The camera is used to place the Daruma in AR.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("3D/Daruma.usdz"),
                .copy("3D/Daruma_texture.png"),
                .copy("Fonts"),
                .copy("Image"),
                .copy("Sound"),
                .copy("Movie")
            ]
        )
    ],
    swiftLanguageModes: [.v6]
)
